POST http://localhost:3001/auth/register HTTP/1.1
content-type: application/json

{
    "username": "test",
    "password": "test"
}
###

POST http://localhost:3001/auth/login HTTP/1.1
content-type: application/json

{
    "username": "test",
    "password": "test"
}
###

GET http://localhost:3001/auth/test HTTP/1.1
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTY3MzQ2NDk4MSwiZXhwIjoxNjczNTUxMzgxfQ.5oMQzs7QT1xBoowleEUNBX12D-6cgyH1YAx77EaYxVE